---
openapi: 3.0.0
info:
  title: Simple Inventory API
  description: This is a simple API
  contact:
    email: you@your-company.com
  version: 1.0.0
servers:
- url: /
tags:
- name: characters
  description: in-game character management
paths:
  /characters/pickupitem:
    post:
      tags:
      - characters
      summary: an item is added to the inventory
      description: takes an item and adds it to the user's inventory
      operationId: app.addItem
      requestBody:
        description: item to add to inventory
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/itemAdded'
      responses:
        "201":
          description: inventory avaliable, item added
        "400":
          description: invalid input, object invalid
    get: 
      tags: 
        - characters 
      summary: get new item event
      operationId: app.getlastitem 
      description: gets the latest item gain event
      parameters: 
        - name: timestamp 
          in: query 
          description: Limits the number of items on a page 
          schema: 
            type: string 
            format: date-time 
            example: 2022-03-03 11:38:40.097
        - name: end_timestamp
          in: query
          description: Limits the end time of the query
          schema:
            type: string
            format: date-time
            example: 2022-03-03 11:38:40.097 
      responses: 
        '200': 
          description: Successfully returned a list of xo events
          content: 
            application/json: 
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/itemAdded' 
        '400': 
          description: Invalid request 
          content: 
            application/json: 
              schema: 
                type: object 
                properties: 
                  message: 
                    type: string        
  /characters/levelup:
    post:
      tags:
      - characters
      summary: advances the character's experience level
      description: adds X to the currently selected character's Xp pool
      operationId: app.addXP
      requestBody:
        description: character that recieves the level up
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/characterXPGained'
      responses:
        "201":
          description: XP added
        "400":
          description: invalid input, object invalid
    get: 
      tags: 
        - characters 
      summary: get new xp event
      operationId: app.getlastxp 
      description: gets the latest xp gain event
      parameters: 
        - name: timestamp 
          in: query 
          description: Limits the number of items on a page 
          schema: 
            type: string 
            format: date-time 
            example: 2022-03-03 11:38:40.097
        - name: end_timestamp
          in: query
          description: Limits the end time of the query
          schema:
            type: string
            format: date-time
            example: 2022-03-03 11:38:40.097
      responses: 
        '200': 
          description: Successfully returned a list of xo events
          content: 
            application/json: 
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/characterXPGained' 
        '400': 
          description: Invalid request 
          content: 
            application/json: 
              schema: 
                type: object 
                properties: 
                  message: 
                    type: string        
components:
  schemas:
    characterXPGained:
      required:
      - characterId
      - timestamp
      - userId
      - xpAmount
      type: object
      properties:
        characterId:
          type: integer
          example: 66542
        xpAmount:
          type: integer
          example: 2000
        userId:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        timestamp:
          type: string
          format: date-time
          example: 2022-03-03 11:38:40.097
        traceid:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
    itemAdded:
      required:
      - characterId
      - itemID
      - itemQuantity
      - timestamp
      type: object
      properties:
        characterId:
          type: integer
          example: 65542
        itemID:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        itemQuantity:
          type: integer
          example: 2
        timestamp:
          type: string
          format: date-time
          example: 2022-03-03 11:38:40.097
        traceid:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
